base_model: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: BhabhaAI/DEITA-Complexity
    type:
      system_prompt: "You are a helpful assistant. Please identify the complexity score of the following user query."
      field_system: system
      field_instruction: prompt
      field_output: score
      format: "[INST] {instruction} [/INST]"
dataset_prepared_path: last_run_prepared
output_dir: ./qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 6
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false

bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
logging_steps: 1

flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 10
evals_per_epoch: 4

eval_max_new_tokens: 128
saves_per_epoch: 1

weight_decay: 0.01

special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"